version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: db.env
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./search_data:/search_data

volumes:
  pg-data: