# Copyright (C) 2022-2023 Magenta Health Inc. and Carmen La

# This file is part of the DFD Story Discovery Tool.

# The DFD Story Discovery Tool is free software: you can redistribute it 
# and/or modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# The DFD Story Discovery Tool is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with the DFD Story Discovery Tool.
# If not, see <https://www.gnu.org/licenses/>.

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: db.env
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./search_data:/search_data

volumes:
  pg-data: